### PR TITLE
Fix: Corrected app.js path

### PR DESCRIPTION
**Pull request by alanaasmaa**

### CODE REVIEW

**Comment by RomainLanz** [comment]
Hey @alanaasmaa! 👋 

`start/app.js` is correct. You may still be on 3.2.

**Comment by alanaasmaa** [comment]
@RomainLanz wowm didnt know about adonisjs 4. It seems its upgrade time. Thanks !

I didnt get it to work with 3.2, so i hope it works with 4.0

**Comment by RomainLanz** [comment]
Yes, this package is created for 4.0. 😄 
Hope you enjoy it!

**Comment by alanaasmaa** [comment]
Upgrade done :) Thanks !

**Pull request closed without merging**
