### PR TITLE
Adding missing module 'aws-sdk'

### PR DESCRIPTION
**Pull request by mtnptrsn**
I'm creating this pull request due to #7 
Hope this helps :)

### CODE REVIEW

**Comment by RomainLanz** [comment]
Hey @mtnptrsn! 👋 
 
You need to install it yourself if you wanna use S3 driver.

**Comment by mtnptrsn** [comment]
@RomainLanz Gotcha. Could you add that to the documentation? :)

**Comment by RomainLanz** [comment]
Yes, it's planned to rework all the documentation of the framework.
Will provide a simple PR soon to clarify this. 👍

**Comment by mtnptrsn** [comment]
Perfect, thank you.

**Pull request closed without merging**
